# coding: utf-8
Import('env')
env_local = env.Clone()

# build tracing
SConscript( 'tracing/SConscript',     exports={'env':env_local}  )
SConscript( 'performance/SConscript', exports={'env':env_local}  )
