#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(target = 'sample_sokol_mrt',
                source = 'mrt-glfw.c',
                use    = ['3rdparty_glfw',
                          '3rdparty_sokol'
                         ]
               )
    bld.program(target = 'sample_sokol_offscreen',
                source = 'offscreen-glfw.c',
                use    = ['3rdparty_glfw',
                          '3rdparty_sokol'
                         ]
               )

