# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = ['.'] )
# preprocessor definitions
env_local.AppendUnique(CPPDEFINES = [])

# get list of files
files = Glob('*.c*')
    
# build library
common_lib = env_local.StaticLibrary('common',files)
Return('common_lib')
